[metadata.display]
name = "Carbon"
isotope = "[^12]C"
symbol = "C"

# Source: https://en.wikipedia.org/wiki/Carbon
[properties.chemical]
atomic_radius = 70
atomic_mass = 12.011
num_protons = 6
num_neutrons = 6